import { Fleur_De_Leah, Thasadith } from "next/font/google";
import "./globals.css";

const fleurDeLeah = Fleur_De_Leah({
  variable: "--font-title",
  subsets: ["latin"],
  weight: "400",
});

const thasadith = Thasadith({
  variable: "--font-text",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fleurDeLeah.variable} ${thasadith.variable}`}>{children}</body>
    </html>
  );
}
